### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by hm2075** [rainerhahnekamp/sam4sc#12]
after fixing the imports, removing index.ts files and cleaning up my application I now get

RangeError: Maximum call stack size exceeded
    at Observable._trySubscribe (/workspace/xxx/node_modules/rxjs/internal/Observable.js:55:25)

CLI was 13.2.5  and now upgrade to 14.0 next 6 and still same issue

also updated rxjs6 to 7

**Comment by hm2075** [comment]
looks like I am stuck for the moment

i am guessing an infinite loop at this point

```
for (const [, { directives }] of Array.from(moduleMap.entries())) {
      for (const directive of directives) {
        rules.push(generateSCAMs(directive.name, directive.type, directive.path));
      }
    }
    ```

**Comment by rainerhahnekamp** [comment]
Just to verify, you are running the schematic already on a beta of 14? Can you post the complete stacktrace? Thank you

**Comment by hm2075** [comment]
I am running 

```
npx ng generate @angular-architects/sam4sc:scam --dry-run
```
tried it on both 13.2.5 and 14 cli   currently using,  not upgraded angular to 14 yet

```
"@angular/cli": "14.0.0-next.6",
```

got the following

```
Skipping 19 undeclared component(s):
..list of components

Skipping 17 SCAM component(s):
..list of components

RangeError: Maximum call stack size exceeded
    at Observable._trySubscribe (/workspace/frontend/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Observable.js:51:34)
    at Observable.subscribe (/workspace/frontend/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Observable.js:30:22)
    at MergeMapOperator.call (/workspace/frontend/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/mergeMap.js:37:23)
    at Observable.subscribe (/workspace/frontend/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Observable.js:25:31)
    at DefaultIfEmptyOperator.call (/workspace/frontend/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/defaultIfEmpty.js:27:23)
    at Observable.subscribe (/workspace/frontend/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Observable.js:25:31)
    at TakeLastOperator.call (/workspace/frontend/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/takeLast.js:38:23)
    at Observable.subscribe (/workspace/frontend/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Observable.js:25:31)
    at ThrowIfEmptyOperator.call (/workspace/frontend/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/throwIfEmpty.js:30:23)
    at Observable.subscribe (/workspace/frontend/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Observable.js:25:31)
